name: Ubuntu 22.04 Iron Build

on:
  pull_request:
  push:
    branches:
      - iron

jobs:
  Build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:iron-desktop-full-jammy

    steps:
    - name: Update
      timeout-minutes: 2
      run: apt update

    - name: Install PIP
      run: apt install -y python3-pip lcov

    - name: Install colcon tools
      run: python3 -m pip install colcon-lcov-result colcon-coveragepy-result

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.5
      with:
        target-ros2-distro: iron

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
      if: failure()