name: Ubuntu 24.04 Rolling Build

on:
  pull_request:
  push:
    branches:
      - iron

jobs:
  Build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:rolling-desktop-full

    steps:
    - name: Update
      timeout-minutes: 2
      run: apt-get update

    - name: Install PIP
      run: apt-get install -y python3-pip lcov python3-colcon-lcov-result python3-colcon-coveragepy-result

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.5
      with:
        target-ros2-distro: rolling

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
      if: failure()